files:
  - source: /*.xml
    translation: /translations/%two_letters_code%/%original_file_name%
  - source: /Sample.csv
    translation: /translations/%three_letters_code%/%original_file_name%
    first_line_contains_header: 1
    scheme: 'identifier,context,source_or_translation'
